@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class SuperMarioGame{
}

class Mario{
+characterPosition
-moveDirection
+characterStatus
+modelDisplay()
+characterMovement()
+stateJudgement()
+calculateTheCoordinates()
}

class Brick{
+position
-isEffective
}
class NonInteractiveBrick{
+brickCoordinate
+modelDisplay()
}

class InteractiveBrick{
+brickCoordinate
+modelDisplay()
+generateInteraction()
}

class Prop{
-kind
-effect
+generateProp()
}

class Gold{
+position
-effect
-modelDisplay()
+getCharacterPosition()
-stateJudgement()
-appearEffect()
}

class Mushroom{
+position
-effect
-moveDirection
-modelDisplay()
+getCharacterPosition()
-propMovement()
-stateJudgement()
-appearEffect()
}

class Star{
+position
-effect
-modelDisplay()
-moveDirection
+getCharacterPosition()
-propMovement()
-stateJudgement()
-appearEffect()
}

class Monster{
-kind
-effect
}

class ChestnutBoy{
+position
-effect
-moveDirection
+monsterStatus
-modelDisplay()
+getCharacterPosition()
-monsterMovement()
-stateJudgement()
-appearEffect()
}

class Turtle{
+position
-effect
-moveDirection
+monsterStatus
-modelDisplay()
+getCharacterPosition()
-monsterMovement()
-stateJudgement()
-appearEffect()
}

class TurtleShell{
+position
-effect
-moveDirection
+monsterStatus
-modelDisplay()
+getPossibleCharacterPosition()
-monsterMovement()
-stateJudgement()
-appearEffect()
}

class Piranha{
+position
-effect
+monsterStatus
-modelDisplay()
+getCharacterPosition()
-stateJudgement()
-appearEffect()
}

class Castle{
+position
-status
+getCharacterPosition()
+stateJudgement()
}

SuperMarioGame"1" o-down- "1" Mario
SuperMarioGame"1" o-down- "1…*" Brick
SuperMarioGame"1" o-down- "1…*" Monster
SuperMarioGame"1" o-down- "1…*" Prop
SuperMarioGame"1" o-down- "1" Castle

Brick <|-down- "1…*" NonInteractiveBrick
Brick <|-down- "1…*" InteractiveBrick

Prop <|-down- "1…*" Gold
Prop <|-down- "1…*" Mushroom
Prop <|-down- "1…*" Star

Monster <|-down- "1…*" ChestnutBoy
Monster <|-down- "1…*" Turtle
Monster <|-down- "1…*" TurtleShell
Monster <|-down- "1…*" Piranha


@enduml